language: c
env:
  global:
    - secure: "A6R+5QhNWyi/Mzn/z8BpYR/Omfkst4FU4pJ36omyYjs3AJLA3b3txXOxVsqiVDUB8hd9Xs70PSk9Qql+Dv+JeAvE1RD1Z0E8t5A7rjaqcjow5zqrETwtJj/GXs/rYwdsVWKAwRYmRe2ARPUxKHwYlhzE4IZiuLnR7lG2GVeIIyM="
before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- chmod 755 ./.push_test_table.sh
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_deps 
- ./travis-tool.sh install_r RCurl RJSONIO lattice xtable
script: 
- ./travis-tool.sh run_tests
- ./.push_test_table.sh
notifications:
  slack:
    secure: YvyGtGRFC4HJGD4d2Vx6fHU93EliJCHbcf/k9/Rbpl3wtYFZfWKbKL1FHvPw/g3auVebonz8hScnYzR0uYnR3dHSlmj3QrJ3NOePv5QAZRHy7aY/XKRr5JR1Ji/vX1yfbrJDmiYuGMxJVE8l/kbu0TxwDdLletY5nJpwlkHfaW8=
