language: r

env:
  global:
    - secure: "cJ1bDRrAdIRjG+JnsQI9CdA4wQJhJJ2DdCNQ3frl8dotk69z61EiGCFW1Ir1cAY5V/NbHvFHp91HDiSo28ggwqRkEPBOGE44ico5gtVaELu3M/EnkWc2ZwQoN1273Vfdm26QYidqrvWrpLZ0XkFl7Q8xgvBswx30MF7y61+0Hv4="

r_packages:
  - RCurl
  - RJSONIO
  - lattice
  - xtable
  - httr 

before_script:
  - chmod 755 inst/testscripts/.push_test_table.sh

after_success:
  - inst/testscripts/.push_test_table.sh
