language: R
cache: packages
sudo: true
dist: trusty

r:
#  - oldrel
  - release
  - devel

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    # plotly_api_key (for posting to plot.ly)
    - secure: "jlIAFoBGaDWUQDh6oGNb2BgU31/80iioM4y4xwx35yWkGKkNIID1eMEuiIn+/ipLvOVHkPTDS6DYnOtD8EIBpROgAKHFY33gM1h7P6NRxVszzC6WLP2ASnq95DWq36DAC2Oevy05V7nwSRFilPwSt6JLppYUInG+WdaZ+QOSRi4="
    # GITHUB_PAT (for pushing to plotly-test-table)
    - secure: "LHJONgWOo+98vNeFLI7LSJU3RtbMVszlI79GB8CcXmc2mlgM/UtZ5b6RnkNlhmg3Gj1/uObfm/rIybVTwuS1yNpeKv73+gsZOYhobVXiUGVxdRFG/mg5mbqwyWkkuofjPGFlMZCEMgHim37eZzgjSibwVH1LClRDsCoFMCgvgV0="

# installing Rserve from source requires non-standard R build (--enable-R-shlib) 
r_binary_packages:
  - rserve

r_packages:
  - devtools
  
r_github_packages:
  - tidyverse/ggplot2

before_install:
  # mainly for installing sf (which requires units/rgeos/rgdal)
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

before_script:
  - git config --global user.email "cpsievert1@gmail.com"
  - git config --global user.name "cpsievert"
  - echo "Sys.setenv('plotly_username' = 'cpsievert')" > ~/.Rprofile
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD INSTALL ${R_PKG}_*.tar.gz

script:
  # run R CMD check on the non-pull request build
  - sh -c "if [ '$TRAVIS_PULL_REQUEST' = 'false' ]; then R CMD check ${R_PKG}_*.tar.gz --no-manual; fi"
  # we do some fancy stuff on the pull request build that confuses R CMD check
  - sh -c "if [ '$TRAVIS_PULL_REQUEST' != 'false' ]; then Rscript -e 'source(\"plotly/tests/testthat.R\", chdir = T)'; fi"

after_success:
  - cd plotly-test-table
  - Rscript ../plotly/inst/build-push-comment.R
