language: r

env:
  global:
    - secure: "cJ1bDRrAdIRjG+JnsQI9CdA4wQJhJJ2DdCNQ3frl8dotk69z61EiGCFW1Ir1cAY5V/NbHvFHp91HDiSo28ggwqRkEPBOGE44ico5gtVaELu3M/EnkWc2ZwQoN1273Vfdm26QYidqrvWrpLZ0XkFl7Q8xgvBswx30MF7y61+0Hv4="

r_packages:
  - RJSONIO
  - lattice
  - xtable
  - httr
  - devtools

before_script:
  - git config --global user.name "cpsievert"
  - git config --global user.email "cpsievert1@gmail.com"
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table

after_success:
  - cd ..
  - Rscript plotly/inst/testscripts/build-push-comment.R

notifications:
  slack:
    secure: YvyGtGRFC4HJGD4d2Vx6fHU93EliJCHbcf/k9/Rbpl3wtYFZfWKbKL1FHvPw/g3auVebonz8hScnYzR0uYnR3dHSlmj3QrJ3NOePv5QAZRHy7aY/XKRr5JR1Ji/vX1yfbrJDmiYuGMxJVE8l/kbu0TxwDdLletY5nJpwlkHfaW8=
