language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # password is encrypted below
  - echo "Sys.setenv('plotly_username' = 'kjsd')" > ~/.Rprofile

install:
  - ./travis-tool.sh install_deps

before_script:
  - git config --global user.name "cpsievert"
  - git config --global user.email "cpsievert1@gmail.com"
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table

script:
  - Rscript -e "devtools::install(); source('tests/testthat.R', chdir = TRUE)"

after_success:
  - cd ../plotly-test-table
  - ls -R
  - Rscript ../plotly/inst/build-push-comment.R

env:
  global:
    - secure: "fT5AI256qBJ41/XhIGc8EPlbUVTiDPAi6/BRHoaSobGtQG9UkfJgprnPvV5jWb6jXYvg7rIldx+ieEeWRraSwYBknqUectIXkP66h+ffUf2U8VYzXrFSRIinN9czWICJj9SOPkt/S3I3/CfCsQ+DAqDLc/qP1/Q1nKNxy04J/Ok="
    - secure: "JsYD7yQbn4PsuUBEvwJHA5TeG/heCE0StTjDo0ecbmUXETCGCepsBnIZLDCl11PSgiBpxIl0kQXp14nr5eZlOvX4r71/ICwug95t2ec56fRFKW4IXeoINlvlSsEC51SVwufsRVpuM0dwIqnpFU4e55tpL/SRGD9E7f5ygLKillA="
