language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # password is encrypted below
  - echo "Sys.setenv('plotly_username' = 'cddf')" > ~/.Rprofile

install:
  - ./travis-tool.sh install_deps

before_script:
  - git config --global user.name "cpsievert"
  - git config --global user.email "cpsievert1@gmail.com"
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table

script:
  - Rscript -e "devtools::install(); source('tests/testthat.R', chdir = TRUE)"

after_success:
  - cd ../plotly-test-table
  - ls -R
  - Rscript ../plotly/inst/build-push-comment.R

env:
  global:
    # plotly_api_key (for posting to plot.ly)
    - secure: "Itu8PkiqIJspisirAxjggelVDh1A7YMjCotqHYBoMMKLgOFSPI8to4h/Fb+HLSWja2HsS8q3ELMap8u8Q5LWp+DTqT+idRoHRjhjAJ0u7Lci+rPIA1Z2az3sE6RlRVIYxX4GfM1ydeoemMjZn83txDGZADHcDWm2OotAKoyf8aw="
    # GITHUB_PAT (for pushing to plotly-test-table)
    - secure: "LHJONgWOo+98vNeFLI7LSJU3RtbMVszlI79GB8CcXmc2mlgM/UtZ5b6RnkNlhmg3Gj1/uObfm/rIybVTwuS1yNpeKv73+gsZOYhobVXiUGVxdRFG/mg5mbqwyWkkuofjPGFlMZCEMgHim37eZzgjSibwVH1LClRDsCoFMCgvgV0="
    # plotlyjs_full (link to the full offline bundle)
    - secure: "ivxfqGwbzpBpVJe+jVcOBktcmLrT38W/ZapAk/FNDu+yaBhag1eCYErAPPx6Snc4GzwatMt22v4SxAqXQF4SAhTRtmrWVaWnbhzuNqpTkiS6IKEd6EqaoyUZvUTgXh1ruyik00zl3ET9898O3vFfqafodljE0lCLVICHq6ANo68="
    # plotlyjs_no_jq (link to the offline bundle w/o jQuery)
    - secure: "i5cYEs2lCFSYgrSTHMmzzs8hRwAwiz89GpgM16fqUDQz8T1QMWofNugQInS7fIfKL36FoTz8BaiLs2D98/2kDkkZ0LTHnfrdrY9PO+7D+CmL8QeLLp4atBT0i682nwy8RzEqlvB8yAVQo/i0Eh8tmT97pppddsxttZKoUidfOeA=" 
