language: c
env:
  global:
    - secure: "Iv8Mn0khbiynIn8JZncN/Qrf1SFEAksaIunG4A+nJ/K1DXR89UieaTZ7FDfpF37P9Pc9vqe38n2k03fn7a4YSyfzZc7CAiCnwQxghOKtpLJRX0kIerdBd98zmSt0T5QttbZOx1kDBK8N1xLCTPjXSpFfmGf/ZSjy+HGwp88VgKw="
before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- chmod 755 ./.push_test_table.sh
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_deps 
- ./travis-tool.sh install_r RCurl RJSONIO lattice xtable
script: 
- ./travis-tool.sh run_tests
- ./.push_test_table.sh
notifications:
  slack:
    secure: YvyGtGRFC4HJGD4d2Vx6fHU93EliJCHbcf/k9/Rbpl3wtYFZfWKbKL1FHvPw/g3auVebonz8hScnYzR0uYnR3dHSlmj3QrJ3NOePv5QAZRHy7aY/XKRr5JR1Ji/vX1yfbrJDmiYuGMxJVE8l/kbu0TxwDdLletY5nJpwlkHfaW8=
