language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

before_script:
  - git config --global user.name "cpsievert"
  - git config --global user.email "cpsievert1@gmail.com"
  - git clone https://github.com/cpsievert/plotly-test-table.git ../plotly-test-table

script:
  - Rscript -e "devtools::install(); source('tests/testthat.R', chdir = TRUE)"

after_success:
  - cd ..
  - Rscript plotly/inst/build-push-comment.R

env:
  global:
    - secure: "cJ1bDRrAdIRjG+JnsQI9CdA4wQJhJJ2DdCNQ3frl8dotk69z61EiGCFW1Ir1cAY5V/NbHvFHp91HDiSo28ggwqRkEPBOGE44ico5gtVaELu3M/EnkWc2ZwQoN1273Vfdm26QYidqrvWrpLZ0XkFl7Q8xgvBswx30MF7y61+0Hv4="
    - secure: "UVOefBq1mkC4Hpg9OkcolvoEtLNfINBFSE7Xdnvb9WEOTv7xQtw/3uenNJEvVVs+0q+1RJ/lWuifCqrlvVNF+qISFWmqL4KHkSnupmh32i5hRglpUF3S+2GvpAtKz3r1F8sfX4fxgGuvzvSYHFgoJB3JN29zSSAV7Flf656ztUM="
    - secure: "V5K2owU+gvzkh+t7HMZvv5ZXwcpPpbMVFhcq1Vm+t2qvr+rb5K4lXgC+8D0yC8YcxE9eTJ1EPCrsvTVYM6tHOhfX1WzJnGJ8tnGd6GDCdgFW7++Vb0gWl55IAAthkHtvDu54cQ8kZ0lp9oBpSRM/4g5jGqQV7pK1ZmzAwdqZfLw="
